# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('iconfile', models.FileField(upload_to=b'documents/%Y/%m/%d')),
                ('position', models.CharField(choices=[(b'1', b'First'), (b'2', b'Second'), (b'3', b'Third'), (b'4', b'Fourth'), (b'5', b'Fifth'), (b'6', b'Sixth'), (b'7', b'Seventh'), (b'8', b'Eighth'), (b'9', b'Ninth')], max_length=4)),
                ('partner', models.CharField(max_length=256)),
                ('mobiletype', models.CharField(choices=[(b'Android', b'Android'), (b'FeaturePhone', b'other'), (b'Windows', b'Windows'), (b'ios', b'ios')], max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
    ]
