# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 09:27
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
